import { ReferenciaModel } from "src/app/shared/models/referencia.model";
import { ClienteModel } from "../models/clientes.model";

export const CLIENTES: ClienteModel[] = [
    {
        id:1,
        nombre: 'Manuela Espinal',
        numeroDocumento:'',
        direccion: 'Carrera 76 # 91 a 22',
        referenciaUbicacion: '',
        barrio: 'Robledo Kenedy',
        valorRuta:'',
        telefono: '3192323757',
        categoriaSector: 'Lejos-medio',
        ciudad: 'Medellín',
        departamento: 'Antioquia',
        maps:'https://maps.app.goo.gl/mBeRUwr7cNRC8cT39'
    },
    {
        id:2,
        nombre: 'Ana María Arango',
        numeroDocumento:'',
        direccion: 'Carrera 78 # 104 c 14',
        referenciaUbicacion: '',
        barrio: 'Doce de Octubre',
        valorRuta:'',
        telefono: '3126093901',
        categoriaSector:'Lejos-medio',
        ciudad: 'Medellín',
        departamento: 'Antioquia',
        maps:'https://maps.app.goo.gl/Si3p9Gjen4R7fA7W9'
    },
    {
        id:3,
        nombre:'Luisa Fernanda coronel',
        numeroDocumento:'',
        departamento:'Norte de Santander',
        ciudad:'Ocaña',
        direccion: 'Calle 15 10a 88',
        referenciaUbicacion: '',
        valorRuta:'',
        telefono: '3134429501',
        categoriaSector:'',
        barrio:'',
        maps:''
    },
    {
        id:4,
        nombre: 'Valentina Garcia',
        numeroDocumento:'',
        ciudad: 'Envigado',
        departamento: 'Antioquia',
        barrio: 'Barrio Obrero',
        direccion: 'Transversal 34c sur # 33-15',
        referenciaUbicacion: 'Primer piso - El local se llama uñas mágicas',
        valorRuta:'',
        telefono: '3008828621',
        categoriaSector:'Lejos-normal',
        maps:'https://maps.app.goo.gl/E2yZq7RWqLJAuKr6A'
    },
    {
        id:5,
        nombre: 'Slendy',
        numeroDocumento:'',
        barrio: 'San Javier',
        direccion: 'Calle 49 # 102bb 35',
        categoriaSector:'',
        valorRuta:'',
        telefono:'3042890062',
        ciudad: 'Medellín',
        departamento:'Antioquia',
        maps:'https://maps.app.goo.gl/tGn4oDLyrdGtAPo18',
        referenciaUbicacion:'El Socorro'
    },
    {
        id:6,
        nombre:'Diana Aristizabal',
        numeroDocumento:'',
        barrio:'Manrique San Pablo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 35a # 99-56',
        maps:'https://maps.app.goo.gl/NVAjogztKxkwFA2F7',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016056759'
    },
    {
        id:7,
        nombre:'Adriana Vasquez',
        numeroDocumento:'',
        barrio:'La Milagrosa',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 28a # 38f 33',
        maps:'https://maps.app.goo.gl/x1UbTyyRf7WJfWbcA',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono: '3024017191'
    },
    {
        id:8,
        nombre:'Paula Meza',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'Girón',
        departamento:'Santander',
        direccion:'',
        maps:'',
        referenciaUbicacion:'puerto Madero Giron',
        valorRuta:'',
        telefono:'3125416310'
    },
    {
        id:9,
        nombre:'Sofia',
        numeroDocumento:'',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 51 #95-58 un 4 piso',
        referenciaUbicacion:'4 piso',
        maps:'https://maps.app.goo.gl/zQfGmUrmScjGCHZBA',
        valorRuta:'',
        telefono:'3022382467'
    },
    {
        id:10,
        nombre:'Adela Montoya',
        numeroDocumento:'',
        barrio:'Robledo Kennedy',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 75a #90-05',
        maps:'https://maps.app.goo.gl/ZxyrPUFU1AEsXNuRA',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3136834739'
    },
    {
        id:11,
        nombre:'Mary Quiñones',
        numeroDocumento:'',
        barrio:'Santander',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 77e # 114-35',
        maps:'https://maps.app.goo.gl/MvYdL1U1X2RWXHeD6',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3004935583'
    },
    {
        id:12,
        nombre:'Carolina Galeano',
        numeroDocumento:'',
        barrio:'Belén la Nubia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 81 # 18b-23',
        maps:'https://maps.app.goo.gl/ynFA71SPmjDTba1V9',
        referenciaUbicacion:'Una cuadra arriba de migración colombia',
        valorRuta:'',
        telefono:'3114294833'
    },
    {
        id:13,
        nombre:'Nasa Roman',
        numeroDocumento:'',
        barrio:'Urbanización Mantia',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion: 'Calle 14 sur # 58-60 apto 1409 torre 1',
        maps:'https://maps.app.goo.gl/e9M9v3DDu61ZJwaC7',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3206581210'
    },
    {
        id:14,
        nombre:'Ana Maria',
        numeroDocumento:'',
        barrio:'Quintas de la Quinta',
        categoriaSector:'',
        ciudad:'La Estrella',
        departamento:'Antioquia',
        direccion:'Carrera 59#82 sur 88',
        maps:'https://maps.app.goo.gl/8kd14jk4ctSme8SJ8',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043765786'
    },
    {
        id:15,
        nombre:'Lorena',
        numeroDocumento:'',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 84 # 39-56',
        maps:'https://maps.app.goo.gl/htp2X4kYexiUuXt59',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3023982018'
    },
    {
        id:16,
        nombre:'Yassiry Gonzalez',
        numeroDocumento:'',
        barrio:'Enciso',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 28A # 57d 41',
        maps:'https://maps.app.goo.gl/gSMgxLkRN9EoDbok7',
        referenciaUbicacion:'Al lado de la Y. al frente de la julia Agudelo',
        valorRuta:'',
        telefono:'3013542944'
    },
    {
        id:17,
        nombre:'Nataly Martinez',
        numeroDocumento:'',
        barrio:'Gratamira',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 108 # 66-27',
        maps:'https://maps.app.goo.gl/i97Are6VWKgcz4TU6',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3146264292'
    },
    {
        id:18,
        nombre:'Daniela Lujan',
        numeroDocumento:'',
        barrio:'Andalucia la Francia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 110 # 46-35',
        maps:'https://maps.app.goo.gl/hDZTMFnP2dbuQsNn6',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3126213542'
    },
    {
        id:19,
        nombre:'Estefania Ospina',
        numeroDocumento:'',
        barrio:'Castilla',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 66 # 94-51',
        maps:'https://maps.app.goo.gl/cY5dJAh6k7rM2TGL9',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3126201863'
    },
    {
        id:20,
        nombre:'Manuela Correa',
        numeroDocumento:'',
        barrio:'Robledo Miramar',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 92 # 77-30',
        maps:'https://maps.app.goo.gl/iXZYn6oHixA4PmDB8',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3106400070'
    },
    {
        id:21,
        nombre:'Katherin Marcano',
        numeroDocumento:'',
        barrio:'Calazans',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 54a 80-13',
        maps:'https://maps.app.goo.gl/v689vQtChNE4ZyGs7',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3117675208'
    },
    {
        id:22,
        nombre: 'Luisa María Londoño Cañas',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'San José de la Montaña',
        departamento:'Antioquia',
        direccion:'Carrera 20 # 20-15 piso 4',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3127646908'
    },
    {
        id:23,
        nombre:'Alejandra acosta',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'Popayan',
        departamento:'Cauca',
        direccion:'Carrera 11 # 19n 50',
        referenciaUbicacion:'CATAY Apto 1',
        maps:'',
        valorRuta:'',
        telefono:'3044574072 '
    },
    {
        id:24,
        nombre:'Central de belleza',
        numeroDocumento:'',
        barrio:'La Candelaria',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cl. 49 #52-60',
        maps:'https://maps.app.goo.gl/NoeNWwh9BdjbXAqg6',
        referenciaUbicacion:'local 117, Segundo piso preguntar por sol',
        valorRuta:'',
        telefono:''
    },
    {
        id:25,
        nombre:'Yesenia Hernadez',
        numeroDocumento:'',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cra 49 b # 95-56 int 401',
        maps:'https://maps.app.goo.gl/JdShTG4mmCFMCAAf8',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043961578'
    },
    {
        id:26,
        nombre:'Ana María Orozco',
        numeroDocumento:'',
        barrio:'Buenos Aires',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 27 # 45-51 apt 301',
        maps:'https://maps.app.goo.gl/SxxXYVxM665JkKncA',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3059168175'
    },
    {
        id:27,
        nombre:'Jesica Osorio',
        numeroDocumento:'',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 79 # 34a 105',
        maps:'https://maps.app.goo.gl/E5XPCqatNHtpXqqh9',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3002325120'
    },
    {
        id:28,
        nombre:'Katherine Andrade',
        numeroDocumento:'',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 107 # 38-23',
        maps:'https://maps.app.goo.gl/ix2khvQh87NX6a2t6',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3165864367'
    },
    {
        id:29,
        nombre:'Evelin Arboleda',
        numeroDocumento:'',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 35 99-39(interior 201)',
        maps:'https://maps.app.goo.gl/ZTuhQeSa3FfQ5Rgs8',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3115662684'
    },
    {
        id:30,
        nombre:'Valeria Ocampo Higuita',
        numeroDocumento:'',
        barrio:'Villatina',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Diagonal 17 C cll 56 A 31',
        maps:'https://maps.app.goo.gl/iLw3hGRjHc6ZXwb47',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3023507294'
    },
    {
        id:31,
        nombre:'Angel Colina',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'',
        departamento:'Bucaramanga',
        direccion:'Calle 42 #36-31 cabecera',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3046453981'
    },
    {
        id:32,
        nombre:'Sara Rodriguez',
        numeroDocumento:'',
        barrio:'Poblado',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cll 7 #39-107',
        maps:'https://maps.app.goo.gl/fMosiiA424miygVn7',
        referenciaUbicacion:'Edificio medical',
        valorRuta:'',
        telefono:'3235264956'
    },
    {
        id:33,
        nombre:'Mary luz Ceballos Montoya',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'Campamento',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3145558335'
    },
    {
        id:34,
        nombre:'Alexandra',
        numeroDocumento:'',
        barrio:'Santander',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 76d # 108a 40',
        maps:'https://maps.app.goo.gl/3RvZzWuxGgM14xKE8',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3022428375'
    },
    {
        id:35,
        nombre:'Juliana cano',
        numeroDocumento:'',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 40 # 104-4 apto 401',
        maps:'https://maps.app.goo.gl/iWA8uQt9ujiBUDj88',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3059060090'
    },
    {
        id:36,
        nombre:'Naomi Álvarez',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Carrera 50 # 48-18',
        maps:'https://maps.app.goo.gl/DR2WRHRnK9TJbS2c7',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3116302277'
    },
    {
        id:37,
        nombre:'María Lorena Cano',
        numeroDocumento:'',
        barrio:'Belencito',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 34b # 106-83 int 304',
        maps:'https://maps.app.goo.gl/6yi9TaNqccMVK6fx9',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3136219584'
    },
    {
        id:38,
        nombre:'Diana Delgado González',
        numeroDocumento:'',
        barrio:'El Cerro',
        categoriaSector:'',
        ciudad:'Barrancabermeja',
        departamento:'Santander',
        direccion:'Calle 29b # 37-07',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3125250978'
    },
    {
        id:39,
        nombre:'Carolina Mira',
        numeroDocumento:'',
        barrio:'',
        categoriaSector:'',
        ciudad:'Remedios',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3146958231'
    },
    {
        id:40,
        nombre:'Laura Restrepo',
        numeroDocumento:'',
        barrio:'Floresta',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 45f # 80-16',
        maps:'https://maps.app.goo.gl/YULqGCytb3AtY7Aq9',
        referenciaUbicacion:'Al frente de las canchas sintéticas',
        valorRuta:'',
        telefono:'3002020861'
    },
    {
        id:41,
        nombre:'María Paulina Quintero',
        numeroDocumento:'',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 89A # 31-39',
        maps:'https://maps.app.goo.gl/DpWU7VWhBGN3BWaX7',
        referenciaUbicacion:'Siempre hay un señor sentado',
        valorRuta:'',
        telefono:'3023611750'
    },
    {
        id:42,
        nombre:'Maryory Osorio',
        numeroDocumento:'',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 19 # 70-75',
        maps:'https://maps.app.goo.gl/mPQfYaegioyDSxgY6',
        referenciaUbicacion:'Diagonal al Aeroparque',
        valorRuta:'',
        telefono:'3027000905'
    },
    {
        id:43,
        nombre:'Isabella',
        numeroDocumento:'',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 78 # 42-82',
        maps:'https://maps.app.goo.gl/cFUnrJX1Nsx6eXN78',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016548352'
    },
    {
        id:44,
        nombre:'Sofia Rincon',
        numeroDocumento:'',
        barrio:'Buenos Aires',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 50a # 20-56',
        maps:'https://maps.app.goo.gl/qJQbNNExhqXbXRBu6',
        referenciaUbicacion:'Unidad cerrada, detrás del centro comercial la central',
        valorRuta:'',
        telefono:'3196347277'
    },
    {
        id:43,
        nombre:'Manuela Perez',
        numeroDocumento:'',
        barrio:'Bomboná',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 40 # 48-95 Local 0169',
        maps:'https://maps.app.goo.gl/2HbfNi1ppixPV4ct7',
        referenciaUbicacion:'En el centro comercial Tranvía Plaza Local 0169',
        valorRuta:'',
        telefono:'3045239933'
    },
    {
        id:44,
        nombre:'Maria Isabel',
        numeroDocumento:'',
        barrio:'Boyacá las Brisas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 112a # 64d 60',
        maps:'https://maps.app.goo.gl/T8RLgDiN8zZ35J9F8',
        referenciaUbicacion:'Por la estación de policía carabineros',
        valorRuta:'',
        telefono:'3128882333'
    },
    {
        id:45,
        nombre:'Adriana Labrador',
        numeroDocumento:'',
        barrio:'Floresta',
        categoriaSector:'Estrato alto',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 48a 81a 50',
        maps:'https://maps.app.goo.gl/3tj9c75pwYRQqzAk9',
        referenciaUbicacion:'En todo el parque John F. Kennedy, parque del amor',
        valorRuta:'',
        telefono:'3197523370'
    },
    {
        id:46,
        nombre:'Santiago Muñoz',
        numeroDocumento:'',
        barrio:'Belén Rosales',
        categoriaSector:'Estrato alto',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 73 # 30b 17',
        maps:'https://maps.app.goo.gl/cQLvV42VPY9T3cWs9',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3135282884'
    },
    {
        id:47,
        nombre:'María Camila Bustamante Giraldo',
        numeroDocumento:'1097040760',
        barrio:'',
        categoriaSector:'',
        ciudad:'Quimbaya',
        departamento:'Quindio',
        direccion:'Calle 14 # 7-28 local 4',
        maps:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3204363897'
    },
    {
        id:48,
        nombre:'Daniela Ruiz',
        barrio:'Villa Hermosa',
        categoriaSector:'Centro-alto',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 66D # 40-30',
        maps:'https://maps.app.goo.gl/1AbhmiRrsAPtAuM68',
        numeroDocumento:'',
        referenciaUbicacion:'Cerca del batallón Girardot',
        valorRuta:'',
        telefono:'3158788669'
    },
    {
        id:49,
        nombre:'María José Taborda',
        barrio:'Castilla',
        categoriaSector:'Norte centro',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 69 # 97-87',
        maps:'https://maps.app.goo.gl/ZErUaAVXBYShaUG36',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3205859204'
    },
    {
        id:50,
        nombre:'Dahia Ramirez',
        barrio:'Caicedo',
        categoriaSector:'Centro-bajo',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 53 # 27-18',
        maps:'https://maps.app.goo.gl/W96YcqPLh9rduak1A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3007147970'
    },
    {
        id:51,
        nombre:'Valentina Penagos',
        barrio:'Robledo Kennedy',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 77 # 89 - 111',
        maps:'https://maps.app.goo.gl/5CqgVVk8AFAPMuby6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3002389085'
    },
    {
        id:52,
        nombre:'Daniela Ospina',
        barrio:'Alfonso Lopez',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 69 # 91-8',
        maps:'https://maps.app.goo.gl/ctaA35vaLyFvDDsz7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3012975585'
    },
    {
        id:53,
        nombre:'Juliana Salazar',
        barrio:'Lopez de Mesa',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 74a # 80b 45',
        maps:'https://maps.app.goo.gl/1RNQa6cvLsDzSowE8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3003620485'
    },
    {
        id:54,
        nombre:'Manuela Muñeton Vásquez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Vegachi',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        numeroDocumento:'1007222946',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3116041945'
    },
    {
        id:55,
        nombre:'Ximena Villa',
        barrio:'Doce de Octubre',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 80 # 107a 11',
        maps:'https://maps.app.goo.gl/CC6zuM8Zi2p6BEQK9',
        numeroDocumento:'',
        referenciaUbicacion:'Dos cuadras arriba de la biblioteca',
        valorRuta:'',
        telefono:'3017442700'
    },
    {
        id:56,
        nombre:'Valentina Patiño',
        barrio:'Alfonso Lopez',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 74 # 89a 51',
        maps:'https://maps.app.goo.gl/KjReqjB6GoH3CMDLA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3006610129'
    },
    {
        id:57,
        nombre:'Jasmin Morales',
        barrio:'Santander',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 115 # 77-62',
        maps:'https://maps.app.goo.gl/UZCGdBLdqKQceBWGA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043854791'
    },
    {
        id:58,
        nombre:'Isabella',
        barrio:'Belén las Mercedez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 31d # 87c 11',
        maps:'https://maps.app.goo.gl/e8Eepy9ooxyPaZT48',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043881035'
    },
    {
        id:59,
        nombre:'Laura',
        barrio:'Belén la Gloria',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 80aa # 19a - 26',
        maps:'https://maps.app.goo.gl/pwfcaGU7mWEpS9Wx8',
        numeroDocumento:'',
        referenciaUbicacion:'A la vuelta de Migración Colombia',
        valorRuta:'',
        telefono:'3005686921'
    },
    {
        id:60,
        nombre:'Xiomara Giraldo',
        barrio:'La Milagrosa',
        categoriaSector:'Normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 28b # 38f 228',
        maps:'https://maps.app.goo.gl/uAWrEvVRuHU91KbZ7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016602400'
    },
    {
        id:61,
        nombre:'Marian Betancur',
        barrio:'Santa Cruz',
        categoriaSector:'Extremo Medellín - parte baja - normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 99 # 50b 07',
        maps:'https://maps.app.goo.gl/khtrY2BY1rtLKRN39',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3002477456'
    },
    {
        id:62,
        nombre:'Luz Edilma Jaramillo',
        barrio:'',
        categoriaSector:'',
        ciudad:'Remedios',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        numeroDocumento:'32212568',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3148503475'
    },
    {
        id:63,
        nombre:'Diana Builes',
        barrio:'La Milagrosa',
        categoriaSector:'Medio alto - normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 28 # 40a 20',
        maps:'https://maps.app.goo.gl/HCrtpFbcA35b6EkNA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3006806537'
    },
    {
        id:64,
        nombre:'Viviana Mazo',
        barrio:'Robledo las Margaritas',
        categoriaSector:'Arriba alto - normal en día',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 62ab # 108 39',
        maps:'https://maps.app.goo.gl/Nodsa31tPsnuSVeh9',
        numeroDocumento:'',
        referenciaUbicacion:'En toda la cancha de robledo las margaritas',
        valorRuta:'',
        telefono:'3005497792'
    },
    {
        id:65,
        nombre:'Esmeralda',
        barrio:'Doce de Octubre',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 82 # 106c 08',
        maps:'https://maps.app.goo.gl/91yPdF5RbZ83Wi8SA',
        numeroDocumento:'',
        referenciaUbicacion:'Al frente de una virgencita',
        valorRuta:'',
        telefono:'3244720049'
    },
    {
        id:66,
        nombre:'Katherine Jaramillo',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 85a 52a -25',
        maps:'https://maps.app.goo.gl/PBB8WVWFrf61KWxo6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3112164629'
    },
    {
        id:67,
        nombre:'Yuliana Arboleda',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 44 # 101 69',
        maps:'https://maps.app.goo.gl/2Fo2LziZh4JyrbiR8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3127307092'
    },
    {
        id:68,
        nombre:'Emily',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 81a # 33aa 93',
        maps:'https://maps.app.goo.gl/JcJT4nCEaYWhypk8A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3044574511'
    },
    {
        id:69,
        nombre:'Libanes Castro',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 80c # 18-63',
        maps:'https://maps.app.goo.gl/NwhJpJqXZvDhnfqy8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3142014480'
    },
    {
        id:70,
        nombre:'Yormary Gudiño',
        barrio:'Villa Hermosa',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 66 # 39A 51 local 9',
        maps:'https://maps.app.goo.gl/FEv6x6mvizD9cyvZA',
        numeroDocumento:'',
        referenciaUbicacion:'Frente a la parada de los buses del parque Villa hermosa',
        valorRuta:'',
        telefono:'3053001863'
    },
    {
        id:71,
        nombre:'Emily Garcia',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 82A # 35-45',
        maps:'https://maps.app.goo.gl/Uv6rArSGHZf1TdvR9',
        numeroDocumento:'',
        referenciaUbicacion:'Simón Bolívar',
        valorRuta:'',
        telefono:'3186023027'
    },
    {
        id:72,
        nombre:'Vanessa Ospina',
        barrio:'Castilla',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 72 # 99-48',
        maps:'https://maps.app.goo.gl/xabtfJaVD661uyik9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3014219444'
    },
    {
        id:73,
        nombre:'Alejandra Muñoz Romero',
        barrio:'',
        categoriaSector:'',
        ciudad:'Puerto Boyacá',
        departamento:'Boyacá',
        direccion:'Carrera 5 # 30 a-17',
        maps:'',
        numeroDocumento:'1018423245',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3028517605'
    },
    {
        id:74,
        nombre:'Laura Castrillon',
        barrio:'Suramericana',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 66 # 49B-20 Centro Comercial Los Sauces',
        maps:'https://maps.app.goo.gl/oKyKFzNcSBb7at8N9',
        numeroDocumento:'',
        referenciaUbicacion:'Centro Comercial Los Sauces, Bloque A - Consultorio 222, cerca al exito de Colombia',
        valorRuta:'',
        telefono:'3166517965'
    },
    {
        id:75,
        nombre:'Valentina Restrepo',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 31 bb # 89 dd 57',
        maps:'https://maps.app.goo.gl/etYPwnSDAUusWawd9',
        numeroDocumento:'',
        referenciaUbicacion:'Altos del Castillo etapa 2',
        valorRuta:'',
        telefono:'3173215402'
    },
    {
        id:78,
        nombre:'Laura Vergara',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 85 # 19 a 34',
        maps:'https://maps.app.goo.gl/zEpyqFmBiWH33crk8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3054399258'
    },
    {
        id:79,
        nombre:'Nataly Castaño',
        barrio:'Boston',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 50 # 38-12 apt 504',
        maps:'https://maps.app.goo.gl/P9Nr3nc37eZCYyVJA',
        numeroDocumento:'',
        referenciaUbicacion:'Unidad Belgica Plaza',
        valorRuta:'',
        telefono:'3216392558'
    },
    {
        id:80,
        nombre:'Sara Arango',
        barrio:'Calasanz',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 98 # 50a-30',
        maps:'https://maps.app.goo.gl/kLfjgsYzA2ihMCKM7',
        numeroDocumento:'',
        referenciaUbicacion:'Urbanizacion Girasoles ',
        valorRuta:'',
        telefono:'3126769801'
    },
    {
        id:81,
        nombre:'Valentina Aguirre Zafra',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 81 # 26-18',
        maps:'https://maps.app.goo.gl/T7NjbSX9id9Lzt6DA',
        numeroDocumento:'',
        referenciaUbicacion:'Sobre toda la avenida 80',
        valorRuta:'',
        telefono:'3004174080'
    },
    {
        id:82,
        nombre:'Estefania Parra',
        barrio:'Florencia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 111a # 68a-93 piso 1',
        maps:'https://maps.app.goo.gl/PjRcLXytMsXuQ2vS9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3106634395'
    },
    {
        id:83,
        nombre:'Elimar Cedeño',
        barrio:'Las Palmas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 35 # 15b-35 local 107',
        maps:'https://maps.app.goo.gl/86TZjn1no57UvRRX7',
        numeroDocumento:'',
        referenciaUbicacion:'Centro de negocios Prisma',
        valorRuta:'',
        telefono:'3026414685'
    },
    {
        id:84,
        nombre:'Javier Pinto',
        barrio:'Poblado',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 10 a # 41-3',
        maps:'https://maps.app.goo.gl/FgKSNGbbXkT1gt8V8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3186583205'
    },
    {
        id:85,
        nombre:'Michelle',
        barrio:'Alfonso Lopez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 91 # 74-40',
        maps:'https://maps.app.goo.gl/m5a2UhvFTHKAn93KA',
        numeroDocumento:'',
        referenciaUbicacion:'Clienta mala clase',
        valorRuta:'',
        telefono:'3167460252'
    },
    {
        id:86,
        nombre:'Reinel Sanchez',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 30A # 82A-27 interior 301',
        maps:'https://maps.app.goo.gl/irfLynwFmFGbeKCK6',
        numeroDocumento:'',
        referenciaUbicacion:'Al frente del centro comercial los molinos',
        valorRuta:'',
        telefono:'3245269408'
    },
    {
        id:87,
        nombre:'Ana Maria Salazar',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 31 # 80a-48',
        maps:'https://maps.app.goo.gl/p3UuS3Nzin2RC3Ex9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3024527462'
    },
    {
        id:88,
        nombre:'Natalia Hincapié',
        barrio:'Belén Buena Vista',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 88 # 18a 44',
        maps:'https://maps.app.goo.gl/5ipWTGejNXdd2ZQZ7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3108588028'
    },
    {
        id:89,
        nombre:'Sara Sofia Pulgarín',
        barrio:'Robledo Pilarica',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 75 # 75-88 apto 405',
        maps:'https://maps.app.goo.gl/pb4uowcph5NyvWNx7',
        numeroDocumento:'',
        referenciaUbicacion:'Edificio Guacarí',
        valorRuta:'',
        telefono:'3013431338'
    },
    {
        id:90,
        nombre:'Maria Camila Correa',
        barrio:'Doce de Octubre',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 106 # 78c 31',
        maps:'https://maps.app.goo.gl/CgziVMNTzazBeLFv9',
        numeroDocumento:'',
        referenciaUbicacion:'Callejones sin acceso a moto',
        valorRuta:'',
        telefono:'3017742615'
    },
    {
        id:91,
        nombre:'Stefany Muñoz',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 100 # 35 a 10',
        maps:'https://maps.app.goo.gl/RYnqgvKnE6VnHeYY7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3193448950'
    },
    {
        id:92,
        nombre:'Ana Sofía Londoño',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 43b # 120-57 Unidad Quintas de San Javier',
        maps:'https://maps.app.goo.gl/gXTF2erJq2nSXooMA',
        numeroDocumento:'',
        referenciaUbicacion:'manzana p, casa 7 primer piso',
        valorRuta:'',
        telefono:'3126140431'
    },
    {
        id:93,
        nombre:'Astrid Carolina Joya Mercado',
        barrio:'La Milagrosa',
        categoriaSector:'',
        ciudad:'Zulia',
        departamento:'Norte de Santander',
        direccion:'Avenida 3 # 1-220',
        maps:'',
        numeroDocumento:'1090364276',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3118858083'
    },
    {
        id:94,
        nombre:'Camila',
        barrio:'La Milagrosa',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 28 # 40a-20',
        maps:'https://maps.app.goo.gl/6Tx87V8Wofb8xwbS7',
        numeroDocumento:'',
        referenciaUbicacion:'Misma ubicación de Diana Builes',
        valorRuta:'',
        telefono:'3244989468'
    },
    {
        id:95,
        nombre:'Yised Velez',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 78 # 35-98',
        maps:'https://maps.app.goo.gl/dCKepkqz3N9x97xp7',
        numeroDocumento:'',
        referenciaUbicacion:'En toda una equina de romboy',
        valorRuta:'',
        telefono:'3003867635'
    },
    {
        id:96,
        nombre:'Angie Ramirez',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 73#45-61 apto 301',
        maps:'https://maps.app.goo.gl/WAPsumFuuRnHQvxi7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3126156273'
    },
    {
        id:97,
        nombre:'Iraida Rojas',
        barrio:'Poblado',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 10 # 42-45',
        maps:'https://maps.app.goo.gl/rKyukvXVVbqbSQVa9',
        numeroDocumento:'',
        referenciaUbicacion:'Edificio la plaza del poblado, local 263 segundo piso',
        valorRuta:'',
        telefono:'3024091201'
    },
    {
        id:98,
        nombre:'Estefany',
        barrio:'Robledo Kennedy',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 75b # 91a 41',
        maps:'https://maps.app.goo.gl/oj3U4h6v6xLUn3oL9',
        numeroDocumento:'',
        referenciaUbicacion:'Normal en día',
        valorRuta:'',
        telefono:'3205553559'
    },
    {
        id:99,
        nombre:'Yenifer Córdoba',
        barrio:'Enciso',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cl 56 fb # 18 bb 16',
        maps:'https://maps.app.goo.gl/93QdjxQpc4f79RiB9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3233077839'
    },
    {
        id:100,
        nombre:'Melisa Alvarez',
        barrio:'Villa Paula',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Calle 55 # 50-94',
        maps:'https://maps.app.goo.gl/arjAXYyaBcU3vWpb6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3196414303'
    },
    {
        id:101,
        nombre:'Estefany Villegas ',
        barrio:'Guayabal',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cra 54 #4-79',
        maps:'https://maps.app.goo.gl/L6HVDgctKuiWTtWt7',
        numeroDocumento:'',
        referenciaUbicacion:'Campo Amor',
        valorRuta:'',
        telefono:'3245074832'
    },
    {
        id:102,
        nombre:'Brenda Guerra Argoti',
        barrio:'Buenos Aires',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 11C # 45cc 05',
        maps:'https://maps.app.goo.gl/eiN3dZ8mvGgJyc6K9',
        numeroDocumento:'',
        referenciaUbicacion:'Al lado del supermercado de la pastora ',
        valorRuta:'',
        telefono:''
    },
    {
        id:103,
        nombre:'Paula Ramírez',
        barrio:'San Germán',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 77 # 60-70 urbanización citrino apto 411',
        maps:'https://maps.app.goo.gl/9EAa6nRDfv6jxjR49',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3194020963'
    },
    {
        id:104,
        nombre:'Ana María',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 107 # 35-79',
        maps:'https://maps.app.goo.gl/d5upz7vEAiuEfxof8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3217698890'
    },
    {
        id:105,
        nombre:'Anderson',
        barrio:'Buenos Aires',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 48 # 30-05',
        maps:'https://maps.app.goo.gl/KgKEewjKCsJGeaHV8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3004575802'
    },
    {
        id:106,
        nombre:'Mariana',
        barrio:'Poblado',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 23 sur número 25b 114 Casa 103',
        maps:'https://maps.app.goo.gl/uGgcDrEWi9e72tyB6',
        numeroDocumento:'',
        referenciaUbicacion:'Montjuic, al frente del mall Distrito Avignon',
        valorRuta:'',
        telefono:'3135563868'
    },
    {
        id:107,
        nombre:'Natalia Ocampo',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 70 # 26A 28',
        maps:'https://maps.app.goo.gl/borJs2Rt2GCxVSk78',
        numeroDocumento:'',
        referenciaUbicacion:'El local se llama Vanidad Divina spa al lado del edificio el candil',
        valorRuta:'',
        telefono:''
    },
    {
        id:108,
        nombre:'Malanie Rios Gonzalez ',
        barrio:'Cr 17#15-21 edificio ltts 15 apto1203',
        categoriaSector:'',
        ciudad:'Pereira',
        departamento:'Risaralda',
        direccion:'',
        maps:'',
        numeroDocumento:'1193214172',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3217575996'
    },
    {
        id:109,
        nombre:'Ingrid Rozo',
        barrio:'',
        categoriaSector:'',
        ciudad:'Villavicencio',
        departamento:'Meta',
        direccion:'Calle 17b #4-50 villa helena o Danubio',
        maps:'',
        numeroDocumento:'1121930909',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3142198497'
    },
    {
        id:110,
        nombre:'María Fernanda',
        barrio:'Robledo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 86 # 77e-03',
        maps:'https://maps.app.goo.gl/7PuvdjeQMLeaX5kd6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016576809 '
    },
    {
        id:111,
        nombre:'Valentina Sierra',
        barrio:'Belén las Violetas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 89 # 30 B 45 int 201',
        maps:'https://maps.app.goo.gl/m9FTfr5g3DqFFutL8',
        numeroDocumento:'',
        referenciaUbicacion:'En toda una esquina',
        valorRuta:'',
        telefono:'3213426683'
    },
    {
        id:112,
        nombre:'Natalia Ardila',
        barrio:'Belén Buena Vista',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 19b # 88A 21',
        maps:'https://maps.app.goo.gl/CcvP2CysYA77m2fo7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3205639848'
    },
    {
        id:113,
        nombre:'Monica Jurado',
        barrio:'',
        categoriaSector:'',
        ciudad:'Bogotá',
        departamento:'Cundinamarca',
        direccion:'Trav 52b # 2-62',
        maps:'',
        numeroDocumento:'43556167',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3118792002'
    },
    {
        id:114,
        nombre:'Valeria Zapata',
        barrio:'Castilla',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 92F #69-09',
        maps:'https://maps.app.goo.gl/78cMmLcCFQZvQw6z9',
        numeroDocumento:'',
        referenciaUbicacion:'Por el hospital la Maria',
        valorRuta:'',
        telefono:'3026005472'
    },
    {
        id:115,
        nombre:'Manuela Barrera ',
        barrio:'Doce de Octubre',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 112 # 81-56',
        maps:'https://maps.app.goo.gl/rrTRnc63yBQwMkst8',
        numeroDocumento:'',
        referenciaUbicacion:'Maps lo corre un poquito',
        valorRuta:'',
        telefono:'3104715926'
    },
    {
        id:116,
        nombre:'Sofia Montes',
        barrio:'Boyacá las Brisas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 113b # 65-7',
        maps:'https://maps.app.goo.gl/qkj2KDCKngNRX4Lk7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016965797'
    },
    {
        id:117,
        nombre:'Daniela Castro',
        barrio:'Santa Fé',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 20 # 57-53',
        maps:'https://maps.app.goo.gl/s54cnsngHZp4gk9Q7',
        numeroDocumento:'',
        referenciaUbicacion:'Spa manos de Diosa, cerca del zoológico Santa Fé',
        valorRuta:'',
        telefono:'3002246593'
    },
    {
        id:118,
        nombre:'Sara Rodriguez',
        barrio:'Belén Rincón',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cr 79 #1 c 02',
        maps:'https://maps.app.goo.gl/kt3gn24SaUyhE1bv7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3235264956'
    },
    {
        id:119,
        nombre:'Valeria Molina',
        barrio:'Robledo Villa Sofía',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Cr 90c # 83-20 301',
        maps:'https://maps.app.goo.gl/Ter7XyFDiNYYqark6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3216145260'
    },
    {
        id:120,
        nombre:'Natalia Perez',
        barrio:'Robledo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 64 # 94a 46',
        maps:'https://maps.app.goo.gl/RmuG6AXB2HyWDhr16',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3127709814'
    },
    {
        id:121,
        nombre:'Carla',
        barrio:'Campo Valdez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 50 bb # 81-65',
        maps:'https://maps.app.goo.gl/DVKRvAT8FM7KQEsp8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3008929819'
    },
    {
        id:122,
        nombre:'Manuela Alvarez',
        barrio:'Robledo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 76a # 91-34',
        maps:'https://maps.app.goo.gl/BeJNXPckyji3iQEt5',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3136922338'
    },
    {
        id:123,
        nombre:'Luxe Lashes',
        barrio:'Floresta',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 46 # 79-58 int 201',
        maps:'https://maps.app.goo.gl/hEdYt3GGgfLZEN5A9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3195921730'
    },
    {
        id:124,
        nombre:'Edilia jaramillo',
        barrio:'',
        categoriaSector:'',
        ciudad:'Remedios',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        numeroDocumento:'32212568',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3148503475'
    },
    {
        id:125,
        nombre:'Natalia Cardona',
        barrio:'',
        categoriaSector:'',
        ciudad:'Alta Leonora',
        departamento:'Manizales',
        direccion:'Carrera 22 # 52 158',
        maps:'',
        numeroDocumento:'1053868926',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3147549555'
    },
    {
        id:126,
        nombre:'Maria Jose Quiroz',
        barrio:'Guayabal',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 53 # 13a sur 51',
        maps:'https://maps.app.goo.gl/ayY47xYEkAtCgaVb6',
        numeroDocumento:'',
        referenciaUbicacion:'Urbanización entre colinas etapa 1 Apto 309',
        valorRuta:'',
        telefono:'3113804847'
    },
    {
        id:127,
        nombre:'Janeth',
        barrio:'Villa Hermosa',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 66c # 41-4',
        maps:'https://maps.app.goo.gl/DSmSmvubXANpF7cR7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3172202241'
    },
    {
        id:128,
        nombre:'Estefany Gómez',
        barrio:'Santa Ines',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 86 # 32-47',
        maps:'https://maps.app.goo.gl/8qTyfgKLAKgFnjYA9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3194439433'
    },
    {
        id:129,
        nombre:'Carolina',
        barrio:'Belén la Nubia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 19 # 81-17 apto 201',
        maps:'https://maps.app.goo.gl/uaaGwi95nvvp5cYaA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3113732392'
    },
    {
        id:130,
        nombre:'Valentina Pabón',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 27 # 83-59',
        maps:'https://maps.app.goo.gl/YGForAggo9wJ9bjV9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3045982701'
    },
    {
        id:131,
        nombre:'Daniela Gutiérrez ',
        barrio:'Juan XXIII',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 49 a # 99ab 49',
        maps:'https://maps.app.goo.gl/kpkWHMVC1T2YNYpD8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3045468781'
    },
    {
        id:132,
        nombre:'Lina Giraldo',
        barrio:'Pedregal',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Transversal 103a # 74a 70',
        maps:'https://maps.app.goo.gl/cto8Vo96pX5DXGkE6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3195768278'
    },
    {
        id:133,
        nombre:'Lina Suarez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Cali',
        departamento:'Valle',
        direccion:'Carrera 1 A 13 # 69 -55 b/ metropolitano del norte ',
        maps:'',
        numeroDocumento:'67042051',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3005419630'
    },
    {
        id:134,
        nombre:'Isabella Roman',
        barrio:'Caicedo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 53 # 25b 29',
        maps:'https://maps.app.goo.gl/t3i3HkqR1PBP6SS1A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3024013678'
    },
    {
        id:135,
        nombre:'Silvia Mesa',
        barrio:'Loma de las Brujas',
        categoriaSector:'',
        ciudad:'Envigado',
        departamento:'Antioquia',
        direccion:'Calle 37 B sur # 27 17 apto 1113 T3',
        maps:'https://maps.app.goo.gl/JSZ2SfQDuqB677Df9',
        numeroDocumento:'',
        referenciaUbicacion:'Unidad Brujas Campestre',
        valorRuta:'',
        telefono:'3043759768'
    },
    {
        id:136,
        nombre:'Samantha Manco',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'',
        direccion:'Carrera 46 # 86-48',
        maps:'https://maps.app.goo.gl/iMX7rag4uCDK4eAj6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3217427034'
    },
    {
        id:137,
        nombre:'Karen Cortes Cardona',
        barrio:'',
        categoriaSector:'',
        ciudad:'Segovia',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        numeroDocumento:'1007185487',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3222363883'
    },
    {
        id:138,
        nombre:'Natalia Díaz Rojas',
        barrio:'Entre amigos',
        categoriaSector:'',
        ciudad:'Sabaneta',
        departamento:'Antioquia',
        direccion:'Calle 72 sur número 46a 56',
        maps:'https://maps.app.goo.gl/zDf6QMfTNHXtrVRw5',
        numeroDocumento:'',
        referenciaUbicacion:'Barrio entre amigos es una casa primer piso al lado de la costa antioqueña',
        valorRuta:'',
        telefono:'3046686678'
    },
    {
        id:139,
        nombre:'Zaray Medina',
        barrio:'',
        categoriaSector:'',
        ciudad:'Cucutá',
        departamento:'Norte de Santander',
        direccion:'Centro Comercial River Plaza Piso 2, local 220',
        maps:'',
        numeroDocumento:'20517093',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3134580975'
    },
    {
        id:140,
        nombre:'Katerin Yepes',
        barrio:'La América',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 86 # 42c 92',
        maps:'https://maps.app.goo.gl/N7953YRFp9NnhQYP8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3005771568'
    },
    {
        id:141,
        nombre:'Leidy Ramírez',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 51B # 94-34',
        maps:'https://maps.app.goo.gl/yDACLM43EZkL6S8VA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3004978505'
    },
    {
        id:142,
        nombre:'Jennifer Madrid',
        barrio:'Loreto',
        categoriaSector:'Centro-alto',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 32 # 32 a 70',
        maps:'https://maps.app.goo.gl/Fup8fNtT6AqtMsrg9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3234313436'
    },
    {
        id:143,
        nombre:'Claudia Veloza',
        barrio:'',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 105 B # 34 BB 50 interior 301',
        maps:'https://maps.app.goo.gl/UccRvkYzjXERY2gJ6',
        numeroDocumento:'',
        referenciaUbicacion:'La casa de arriba de la licorera JC',
        valorRuta:'',
        telefono:'3146690566'
    },
    {
        id:144,
        nombre:'Carolina',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 69 # 43-35 Apt 201',
        maps:'https://maps.app.goo.gl/PyutGWr5HgRgiSvY7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3215067701'
    },
    {
        id:145,
        nombre:'Lizbey Gaviria',
        barrio:'Popular 2',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 119 # 43c 18',
        maps:'',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016102211'
    },
    {
        id:146,
        nombre:'Melisa Restrepo Álvarez',
        barrio:'Belencito',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 33b # 106-88',
        maps:'https://maps.app.goo.gl/995ZhsAB3srFBycR6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3044245611'
    },
    {
        id:147,
        nombre:'Mariana Bohorquez',
        barrio:'Robledo diamante',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Transversal 79c # 80-53',
        maps:'https://maps.app.goo.gl/nmcTy39cZxZ8YScH8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3006857661'
    },
    {
        id:148,
        nombre:'Karen Terranova',
        barrio:'',
        categoriaSector:'',
        ciudad:'Armenia',
        departamento:'Quindio',
        direccion:'',
        maps:'',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3217996805'
    },
    {
        id:149,
        nombre:'Tatiana Restrepo',
        barrio:'',
        categoriaSector:'',
        ciudad:'Caldas',
        departamento:'Antioquia',
        direccion:'Carrera 49 #135 sur 104 apt 201  barrio hospital',
        maps:'https://maps.app.goo.gl/PWiFYsmH4SjgWEgQ7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3117504921'
    },
    {
        id:150,
        nombre:'Jenni',
        barrio:'Las palmas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 43 # 41-125',
        maps:'https://maps.app.goo.gl/XFhebdoYnpfka9BS9',
        numeroDocumento:'',
        referenciaUbicacion:'Por todo Girardot hasta llegar a un callejón sin salida',
        valorRuta:'',
        telefono:'318 8639687'
    },
    {
        id:151,
        nombre:'Leidy Jimenez',
        barrio:'Campo Valdez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 79 # 49-39',
        maps:'https://maps.app.goo.gl/ruLTVMfxC5aMGVV2A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3164801082'
    },
    {
        id:152,
        nombre:'Camila Ramirez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 78 # 71-129',
        maps:'https://maps.app.goo.gl/KuGK4JDbgy11mTKM7',
        numeroDocumento:'',
        referenciaUbicacion:'Bosques de San Pablo, casa primer piso, Al frente del hospital Pablo tobon Uribe',
        valorRuta:'',
        telefono:'3195580658'
    },
    {
        id:153,
        nombre:'Maryin Rodríguez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Manizales',
        departamento:'Caldas',
        direccion:'Calle 15#21-33 local 1 san Antonio',
        maps:'',
        numeroDocumento:'21465195',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3203709218'
    },
    {
        id:154,
        nombre:'Yuliana Parra',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 9AA # 75-52 3 piso',
        maps:'https://maps.app.goo.gl/vtgxc8dQ89VWH7SdA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3114210267'
    },
    {
        id:155,
        nombre:'Isabella Tapias',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'',
        departamento:'',
        direccion:'Carrera 76a # 16-12',
        maps:'https://maps.app.goo.gl/5gAzwXwMunQGsV5M7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3229417270'
    },
    {
        id:156,
        nombre:'Mariana',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 30c # 89 a 26',
        maps:'https://maps.app.goo.gl/ba4xKoEJrtSdhXQZ9',
        numeroDocumento:'',
        referenciaUbicacion:'Tercer piso, al frente del efecty',
        valorRuta:'',
        telefono:'3022001618'
    },
    {
        id:157,
        nombre:'Camila Suaza',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 1 sur 75 DA 191 apto 407',
        maps:'https://maps.app.goo.gl/E5gs88fVJTn4hvTz7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3017322177'
    },
    {
        id:158,
        nombre:'Brando Smith',
        barrio:'El Salvador',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 35a # 39a-29',
        maps:'https://maps.app.goo.gl/h47Gm4rs7ZDZk3c5A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3014989445'
    },
    {
        id:159,
        nombre:'Elcy Ramirez',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 80 # 35-09',
        maps:'https://maps.app.goo.gl/5B7cR4GPUgtqLAYNA',
        numeroDocumento:'',
        referenciaUbicacion:'Abajo del rompoy de don Quijote, Encima de drogas la rebaja, La entrada es al lado de los vestidos de baño',
        valorRuta:'',
        telefono:'3044351802'
    },
    {
        id:160,
        nombre:'Mariana Castrillon',
        barrio:'Belén',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 20a # 76-34 local primer piso',
        maps:'https://maps.app.goo.gl/qeZkX9Gx7VrLW3qw6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3024556290'
    },
    {
        id:161,
        nombre:'Kelly Gil Zora',
        barrio:'El Carmelo',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Calle 75A #50-15 casa segundo piso',
        maps:'https://maps.app.goo.gl/Yc9Y14fyP2Ci4D126',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3008917661'
    },
    {
        id:162,
        nombre:'Leidy Ortiz',
        barrio:'Villa Paula',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Calle 49 #48-52',
        maps:'https://maps.app.goo.gl/Rtdvwt3HQeo2h4Tm6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3022753280'
    },
    {
        id:163,
        nombre:'Karen Suaza',
        barrio:'',
        categoriaSector:'',
        ciudad:'La Estrella',
        departamento:'Antioquia',
        direccion:'Carrera 59b # 77Sur 86 apt 301',
        maps:'https://maps.app.goo.gl/5DaA4MuYaG64jH5J8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3126079734'
    },
    {
        id:164,
        nombre:'Natalia Bustamante',
        barrio:'',
        categoriaSector:'',
        ciudad:'La Estrella',
        departamento:'Antioquia',
        direccion:'Carrera 50 #95 a sur 97',
        maps:'Carrera 50 #95 a sur 97',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3104020690'
    },
    {
        id:165,
        nombre:'María Fernanda',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 42 # 102-70',
        maps:'https://maps.app.goo.gl/itJrsLPmtTsgNzm87',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3233053766'
    },
    {
        id:166,
        nombre:'Sindy Roldán',
        barrio:'San Javier',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 100B # 45-5',
        maps:'https://maps.app.goo.gl/ggfRmj6UQ9GYTsnNA',
        numeroDocumento:'',
        referenciaUbicacion:'Casa Kolacho',
        valorRuta:'',
        telefono:'3008159585'
    },
    {
        id:167,
        nombre:'Mitchelle Gaviria',
        barrio:'20 de Julio',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 111e # 34dd 96',
        maps:'https://maps.app.goo.gl/vs6cURsFzuDmCMfT8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3052164154'
    },
    {
        id:168,
        nombre:'Vanesa Orozco',
        barrio:'Castilla',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 98 # 70-19',
        maps:'https://maps.app.goo.gl/vSZPH8ZDJRhJga629',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3045823158'
    },
    {
        id:169,
        nombre:'Mariana Franco',
        barrio:'Belalcázar',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 103e 63e 74 Segundo Piso',
        maps:'https://maps.app.goo.gl/6CgVe3iBL1qek8a17',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3007873878'
    },
    {
        id:170,
        nombre:'Evelyn Sanchez',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 84 # 39-64',
        maps:'https://maps.app.goo.gl/myztyXLaCdrHYefH6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3243714464'
    },
    {
        id:171,
        nombre:'Stefanny Londoño',
        barrio:'Loreto',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 33 # 33 A 65 primer piso garaje gris',
        maps:'https://maps.app.goo.gl/qdMjViabntM2ATkh6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3044489871'
    },
    {
        id:172,
        nombre:'Manuela Bedoya',
        barrio:'Pedregal',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 100b 74-64 tercer piso',
        maps:'https://maps.app.goo.gl/67Rqu7a4uNUFamY16',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043751933'
    },
    {
        id:173,
        nombre:'Laura Castrillon Restrepo',
        barrio:'Robledo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 91 # 66-39 interior 202  Villas de Santa Catalina',
        maps:'https://maps.app.goo.gl/RyqVPxLu7fzhpfaD9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3166517965'
    },
    {
        id:174,
        nombre:'Laura Correa',
        barrio:'Florencia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 72a # 113-21 segundo piso',
        maps:'https://maps.app.goo.gl/a3JmMm2UYTeDhDN4A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3175538762'
    },
    {
        id:175,
        nombre:'Mary Arango',
        barrio:'El Socorro',
        categoriaSector:'',
        ciudad:'Caldas',
        departamento:'Antioquia',
        direccion:'Carrera 50 # 133 sur 22 interior 101 casa bonita Centro estético',
        maps:'https://maps.app.goo.gl/NM7bQkWCSWcD8eMM7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3217571992'
    },
    {
        id:176,
        nombre:'Cindy Lorena Triana Hernandez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Montería',
        departamento:'Córdoba',
        direccion:'Calle 37 número 1w-340',
        maps:'',
        numeroDocumento:'1067950076',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3148780471'
    },
    {
        id:177,
        nombre:'Yenifer Florez',
        barrio:'',
        categoriaSector:'',
        ciudad:'Remedios',
        departamento:'Antioquia',
        direccion:'',
        maps:'',
        numeroDocumento:'1020106752',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3148179158'
    },
    {
        id:179,
        nombre:'Julieth Caicedo Acevedo',
        barrio:'',
        categoriaSector:'',
        ciudad:'Cúcuta',
        departamento:'Norte de Santander',
        direccion:'Calle 6AN # 3e - 07 ceiba 2',
        maps:'',
        numeroDocumento:'1090442692',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3153980938'
    },
    {
        id:180,
        nombre:'Sofia Marin',
        barrio:'Poblado',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 17 # 27A-109 torre 3 apto 1903',
        maps:'https://maps.app.goo.gl/Hu9rx1i5AivNzK5P8',
        numeroDocumento:'',
        referenciaUbicacion:'Apartamentos campestres Yerbabuena',
        valorRuta:'',
        telefono:'3045756960'
    },
    {
        id:181,
        nombre:'Miryan Díaz',
        barrio:'Manrique las Granjas',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 86 # 40-14',
        maps:'https://maps.app.goo.gl/98VknNjubvDwFbig8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3152101615'
    },
    {
        id:182,
        nombre:'Jazmin',
        barrio:'Estadio',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 51 #71-07 local 102',
        maps:'https://maps.app.goo.gl/m1Xjpcz6x1w7JWaj9',
        numeroDocumento:'',
        referenciaUbicacion:'Bolerama mixto una cuadra antes del diamante',
        valorRuta:'',
        telefono:'3218476213'
    },
    {
        id:183,
        nombre:'Juliana Salazar',
        barrio:'Alfonso Lopez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 92 # 75b 25',
        maps:'https://maps.app.goo.gl/GTebzeV5Scd8EyYm7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3003620485'
    },
    {
        id:184,
        nombre:'Andrea Reinoso',
        barrio:'Popular 1',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 42bb # 120-40',
        maps:'https://maps.app.goo.gl/iAqcdv5yzKJ7TvDD6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3186391326'
    },
    {
        id:185,
        nombre:'Vannesa',
        barrio:'Rodeo Alto',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 9 sur # 79c 15 Torre 4 apartamento 3220',
        maps:'https://maps.app.goo.gl/7yLiJ4W1uZcBs4nV7',
        numeroDocumento:'',
        referenciaUbicacion:'Mirador de Arboleda',
        valorRuta:'',
        telefono:''
    },
    {
        id:186,
        nombre:'Camila Ramirez',
        barrio:'Caicedo',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 52 # 13-46',
        maps:'https://maps.app.goo.gl/oEqkqbpXZfKJ2BEq7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3196033865'
    },
    {
        id:187,
        nombre:'María Teresa Vargas',
        barrio:'Belén la Nubia',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 18A # 82-53 casa primer piso',
        maps:'https://maps.app.goo.gl/mqjh4BRBY4DcPKuf8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3218479690'
    },
    {
        id:188,
        nombre:'Ashley Restrepo',
        barrio:'Ditaires',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Carrera 65 # 34-81',
        maps:'https://maps.app.goo.gl/CuYeurvJDAb8C4X58',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3243107546'
    },
    {
        id:189,
        nombre:'Vanesa',
        barrio:'Barichara',
        categoriaSector:'',
        ciudad:'San Antonio de Prado',
        departamento:'Antioquia',
        direccion:'Calle 52 a sur #67-157',
        maps:'https://maps.app.goo.gl/xLRJpn3bQXtBYxtd6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3004565911'
    },
    {
        id:190,
        nombre:'Estefany Gómez',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 86 # 32-47',
        maps:'https://maps.app.goo.gl/xz4prCKrrZ8qUtUf6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'319 4439433'
    },
    {
        id:191,
        nombre:'Esmeralda Buritica',
        barrio:'Robledo Diamante',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 78B # 85a 30',
        maps:'https://maps.app.goo.gl/u8mfnQjLvrTddPNv9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3234209766'
    },
    {
        id:192,
        nombre:'Melisa Roldan',
        barrio:'Caribe',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 74 # 64 c 13',
        maps:'https://maps.app.goo.gl/amDRcF3rJz1VxrQBA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3233947982'
    },
    {
        id:193,
        nombre:'Julieth Guzmán',
        barrio:'Buenos Aires',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 25 # 48-5',
        maps:'https://maps.app.goo.gl/qL1edZ9PioYiX4na7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3152261703'
    },
    {
        id:194,
        nombre:'Jazmine',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 82 # 47-47 primer piso',
        maps:'https://maps.app.goo.gl/SeFGWTJLJRitK2Wa8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3044861170'
    },
    {
        id:195,
        nombre:'Monica Monsalve',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 84 # 50 d 26',
        maps:'https://maps.app.goo.gl/Drf5nRuAKC99d7aW8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3508645009'
    },
    {
        id:196,
        nombre:'Ana Maria',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 70 # 43-8',
        maps:'https://maps.app.goo.gl/7Ve1J6KFjaUxgRfq9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3017440618'
    },
    {
        id:197,
        nombre:'María Camila Suaza',
        barrio:'Belén la Mota',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 1 sur 75 DA 191 apto 407',
        maps:'https://maps.app.goo.gl/pWeaBuSwkRdbC1AB8',
        numeroDocumento:'1001237055',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3017322177'
    },
    {
        id:198,
        nombre:'Sara García',
        barrio:'Belencito',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 33b # 102-39',
        maps:'https://maps.app.goo.gl/ost35RiN6Q9E1fgu5',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3156142264'
    },
    {
        id:199,
        nombre:'Paola Andrea Bolivar',
        barrio:'',
        categoriaSector:'',
        ciudad:'Tulua',
        departamento:'Valle',
        direccion:'Calle 24 #37-30 nuevo alvernia',
        maps:'',
        numeroDocumento:'1112105329',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3185213316'
    },
    {
        id:200,
        nombre:'Alison',
        barrio:'Enciso',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 56 # 25-50',
        maps:'https://maps.app.goo.gl/BfiMR56dyH8nbqKX9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3502483421'
    },
    {
        id:201,
        nombre:'Luisa Leal',
        barrio:'Villa Hermosa',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 39 # 65-4 Bloque b apto 108',
        maps:'https://maps.app.goo.gl/fwFFwGTEboESNzDf9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043658424'
    },
    {
        id:202,
        nombre:'Alejandra Arias',
        barrio:'Manzanares',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 2a # 55-5',
        maps:'https://maps.app.goo.gl/TZHcgga3KaNb1aFQ7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3017161943'
    },
    {
        id:203,
        nombre:'Susana Cárdenas',
        barrio:'Pedregal',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 104e # 74-78 3 piso',
        maps:'https://maps.app.goo.gl/LCqwCq9FWfJp8R3V6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3045511058'
    },
    {
        id:204,
        nombre:'Mariano Torres',
        barrio:'Santa Mónica',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 90 # 44c 10',
        maps:'https://maps.app.goo.gl/yt9BuWqGfKvzPSvk8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3127778808'
    },
    {
        id:205,
        nombre:'Karen Tabares',
        barrio:'Santander',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 114 # 76d 53',
        maps:'https://maps.app.goo.gl/wgqfid6Rj4YEF6u2A',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3117271004'
    },
    {
        id:206,
        nombre:'Valentina Cardona',
        barrio:'Santander',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 108 # 79 A 7',
        maps:'https://maps.app.goo.gl/ngHM3EEpe4wnVcAQ8',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3043881032'
    },
    {
        id:207,
        nombre:'Sara Sanchez',
        barrio:'Aranjuez',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 52 # 97-149',
        maps:'https://maps.app.goo.gl/EmSG5LUof8LbUKBT7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3016006653'
    },
    {
        id:208,
        nombre:'Milena Osorio',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 35 # 95-08 piso 2',
        maps:'https://maps.app.goo.gl/KDEfCEVTw5E5t3vf6',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3046229534'
    },
    {
        id:209,
        nombre:'Evelyn',
        barrio:'Boston',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 56 # 32-14',
        maps:'https://maps.app.goo.gl/oS3jbQM1FFtUejmRA',
        numeroDocumento:'',
        referenciaUbicacion:'Garaje blanco',
        valorRuta:'',
        telefono:'3174745237'
    },
    {
        id:210,
        nombre:'Angela',
        barrio:'Estadio',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'CC Obelisco Local 901 piso 8',
        maps:'https://maps.app.goo.gl/TavpAXmWVxRDtAZt7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3148233997'
    },
    {
        id:211,
        nombre:'July Lara, Milena Rendon',
        barrio:'Laureles',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 43 # 79-20 CENTRO ESTÉTICO ',
        maps:'https://maps.app.goo.gl/HZaam8APvbV8ut4x6',
        numeroDocumento:'',
        referenciaUbicacion:'Detrás de la Iglesia La Consolata',
        valorRuta:'',
        telefono:'3126026299'
    },
    {
        id:212,
        nombre:'Yormaira Díaz',
        barrio:'Castilla',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 101 # 68-17',
        maps:'https://maps.app.goo.gl/ueCroYcVfy5S9VUG9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3147944085'
    },
    {
        id:213,
        nombre:'Ximena Herrera',
        barrio:'Playa Rica',
        categoriaSector:'',
        ciudad:'Itagüí',
        departamento:'Antioquia',
        direccion:'Calle 45 A # 53-77',
        maps:'https://maps.app.goo.gl/ftAAoVP8G7jRBk8f9',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3197384166'
    },
    {
        id:214,
        nombre:'Laura',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Calle 72 # 44-105 centro comercial gardel plaza primer piso local 103',
        maps:'https://maps.app.goo.gl/4o7EC4dBrcLofVGVA',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3195078393'
    },
    {
        id:215,
        nombre:'Monica Salas',
        barrio:'Manrique',
        categoriaSector:'',
        ciudad:'Medellín',
        departamento:'Antioquia',
        direccion:'Carrera 32 # 84-40 int 364',
        maps:'https://maps.app.goo.gl/rqFNC4MQq4wNBTrE7',
        numeroDocumento:'',
        referenciaUbicacion:'',
        valorRuta:'',
        telefono:'3007544246'
    }
]

export const SECTOR: ReferenciaModel[]=[
    {
        id:1,
        nombre:'Robledo Miramar'
    },
    {
        id:2,
        nombre:'Doce de Octubre'
    },
    {
        id:3,
        nombre:'San Javier'
    },
    {
        id:4,
        nombre:'Manrique San Pablo'
    },
    {
        id:5,
        nombre:'La Milagrosa'
    },
    {
        id:6,
        nombre:'Barrio Obrero'
    },
    {
        id:7,
        nombre:'Aranjuez'
    },
    {
        id:8,
        nombre:'Robledo Kennedy'
    },
    {
        id:9,
        nombre:'Santander'
    },
    {
        id:10,
        nombre:'Belén la Nubia'
    },
    {
        id:11,
        nombre:'Quintas de la Quinta'
    },
    {
        id:12,
        nombre:'Manrique'
    },
    {
        id:13,
        nombre:'Enciso'
    },
    {
        id:14,
        nombre:'Gratamira'
    },
    {
        id:15,
        nombre:'Andalucia la Francia'
    },
    {
        id:16,
        nombre:'Castilla'
    },
    {
        id:17,
        nombre:'Calazans'
    },
    {
        id:18,
        nombre:'La Candelaria'
    },
    {
        id:19,
        nombre:'Buenos Aires'
    },
    {
        id:20,
        nombre:'Laureles'
    },
    {
        id:21,
        nombre:'Villatina'
    },
    {
        id:22,
        nombre:'Poblado'
    },
    {
        id:23,
        nombre:'Belencito'
    },
    {
        id:24,
        nombre:'Floresta'
    },
    {
        id:25,
        nombre:'Belén'
    },
    {
        id:26,
        nombre:'Boyacá las Brisas'
    },
    {
        id:27,
        nombre:'Belén Rosales'
    },
    {
        id:28,
        nombre:'Villa Hermosa'
    },
    {
        id:29,
        nombre:'Alfonso Lopez'
    },
    {
        id:30,
        nombre:'Lopez de Mesa'
    },
    {
        id:31,
        nombre:'Belén las Mercedez'
    },
    {
        id:32,
        nombre:'Belén la Gloria'
    },
    {
        id:33,
        nombre:'Santa Cruz'
    },
    {
        id:34,
        nombre:'Robledo las Margaritas'
    },
    {
        id:35,
        nombre:'Boston'
    },
    {
        id:36,
        nombre:'Las Palmas'
    },
    {
        id:37,
        nombre:'Belén Buena Vista'
    },
    {
        id:38,
        nombre:'Robledo Pilarica'
    },
    {
        id:39,
        nombre:'Villa Paula'
    },
    {
        id:40,
        nombre:'San Germán'
    },
    {
        id:41,
        nombre:'Campo Valdez'
    },
    {
        id:42,
        nombre:'Loreto'
    },
    {
        id:43,
        nombre:'Caicedo'
    },
    {
        id:44,
        nombre:'Robledo Diamante'
    },
    {
        id:45,
        nombre:'Belén las Violetas'
    },
    {
        id:46,
        nombre:'Juan XXIII'
    },
    {
        id:47,
        nombre:'Santa Fé'
    },
    {
        id:48,
        nombre:'Robledo Villa Sofía'
    },
    {
        id:49,
        nombre:'Belén Rincón'
    },
    {
        id:50,
        nombre:'Entre amigos'
    },
    {
        id:51,
        nombre:'La América'
    },
    {
        id:52,
        nombre:'Popular 2'
    },
    {
        id:53,
        nombre:'El Salvador'
    },
    {
        id:54,
        nombre:'El Carmelo'
    },
    {
        id:55,
        nombre:'20 de Julio'
    },
    {
        id:56,
        nombre:'Pedregal'
    },
    {
        id:57,
        nombre:'Florencia'
    },
    {
        id:58,
        nombre:'El Socorro'
    },
    {
        id:59,
        nombre:'Manrique las Granjas'
    },
    {
        id:60,
        nombre:'Popular 1'
    },
    {
        id:61,
        nombre:'Barichara'
    },
    {
        id:62,
        nombre:'Belén la Mota'
    },
    {
        id:63,
        nombre:'Manzanares'
    },
    {
        id:64,
        nombre:'Playa Rica'
    }
]

export const CATEGORIA_SECTOR: ReferenciaModel[]=[
    {
        id:1,
        nombre:'Lejos-medio'
    },
    {
        id:2,
        nombre:'Lejos-normal'
    },
    {
        id:3,
        nombre:'Arriba-no-peligroso'
    },
    {
        id:4,
        nombre:'Estrato alto'
    },
    {
        id:5,
        nombre:'Centro-alto'
    },
    {
        id:6,
        nombre:'Norte centro'
    },
    {
        id:7,
        nombre:'Normal en día'
    },
    {
        id:8,
        nombre:'Medio alto - normal en día'
    },
    {
        id:9,
        nombre:'Arriba alto - normal en día'
    }
]